### ISSUE TITLE
Deletable based on field in row

### ISSUE THREAD

**Issue by tangjh** [Power-Components/powergrid-demo#3]
I have multiple action icons eg. delete, edit for every row in table.   for each row, there is a data field status that indicates true => row can be deleted, false => row cannot be deleted.

How do I display the delete action trashcan icon button on right side of each row if status is true?  otherwise no icon.

Any example?

**Comment by devsquad-luan-freitas** [comment]
Hi. You tried using the `->can()` method ?

I will close this issue around here, but if it doesn't work, I suggest opening it in the package's own github

**Comment by luanfreitasdev** [comment]
Hi. You tried using the ->can() method ?

I will close this issue around here, but if it doesn't work, I suggest opening it in the package's own github
